import Config

config :static_blog, :app, :localize_blog

config :static_blog, :site,
  title: "Localize",
  tagline: "Next-generation localization for Elixir.",
  description:
    "Development notes, release updates and technical writing about Localize, " <>
      "the next-generation CLDR-based localization library for Elixir.",
  author: "Kip Cole",
  base_url: "https://blog.localize.dev",
  language: "en",
  robots_disallow: ["/locales/"],
  sidebar: [
    %{
      heading: "Projects",
      links: [
        %{
          url: "https://github.com/elixir-localize",
          label: "Localize",
          note: "Next-generation localization for Elixir",
          rel: "me external"
        },
        %{
          url: "https://github.com/elixir-image",
          label: "Image processing",
          note: "Vix, Image and friends for Elixir",
          rel: "external"
        }
      ]
    },
    %{
      heading: "About",
      links: [
        %{url: "/colophon/", label: "Colophon"},
        %{url: "/feed.xml", label: "RSS feed"}
      ]
    }
  ],
  colophon_body: """
  <p>
    This blog is a static website generated by a small Elixir program. This repository holds the content and configuration; the engine itself is a published package. The source is plain markdown; everything else is built from it on demand.
  </p>

  <h2>Build</h2>
  <ul>
    <li>
      <a href="https://elixir-lang.org">Elixir</a> and
      <a href="https://www.erlang.org">Erlang/OTP</a> run the build.
      Mix tasks <code>blog.build</code>, <code>blog.serve</code> and
      <code>blog.publish</code> drive it end to end.
    </li>
    <li>
      <a href="https://hex.pm/packages/static_blog">static_blog</a> is the
      engine: it provides those Mix tasks, the page templates, the feed and
      sitemap generation, and the R2 publisher.
    </li>
    <li>
      <a href="https://hex.pm/packages/nimble_publisher">nimble_publisher</a>
      parses the markdown files in <code>priv/posts/</code> into post
      structs at compile time, rendering markdown to HTML with
      <a href="https://hex.pm/packages/mdex">MDEx</a>.
    </li>
    <li>
      <a href="https://hex.pm/packages/makeup_elixir">makeup_elixir</a>
      and <a href="https://hex.pm/packages/makeup_erlang">makeup_erlang</a>
      provide syntax highlighting for fenced code blocks.
    </li>
    <li>
      <a href="https://hex.pm/packages/phoenix_live_view">Phoenix LiveView</a>'s
      component and HEEx compiler are used — at build time only — to render the
      page templates to HTML. There is no server at runtime.
    </li>
  </ul>

  <h2>Design</h2>
  <ul>
    <li>
      Typography and layout are inspired by
      <a href="https://daringfireball.net">Daring Fireball</a>. Body text
      is set in Verdana, titles in Gill Sans, code in SF Mono.
    </li>
    <li>
      The colour palette is shifted away from the canonical Elixir purple
      into a slightly warmer violet. All body-text pairings meet
      WCAG AAA (≥ 7:1).
    </li>
    <li>
      Light and dark themes are switched by a small inline script that
      reads <code>localStorage</code> and <code>prefers-color-scheme</code>.
      There is no JavaScript framework.
    </li>
  </ul>

  <h2>Accessibility</h2>
  <ul>
    <li>Semantic HTML landmarks, a skip-to-content link, and visible focus outlines.</li>
    <li>Theme toggle is a real button with <code>aria-pressed</code>.</li>
    <li><code>prefers-reduced-motion</code> disables all transitions.</li>
    <li>
      Colour contrast verified with the
      <a href="https://github.com/elixir-image/color">Color</a> library's
      WCAG helpers.
    </li>
  </ul>

  <h2>Hosting</h2>
  <p>
    The generated site is uploaded to a
    <a href="https://www.cloudflare.com/developer-platform/r2/">Cloudflare R2</a>
    bucket using AWS Signature V4 via
    <a href="https://hex.pm/packages/aws_signature">aws_signature</a>
    and transported with <a href="https://hex.pm/packages/req">Req</a>.
    The publisher diffs the local tree against the remote manifest so
    subsequent syncs only upload what has changed.
  </p>

  <h2>Source</h2>
  <p>
    The blog's source — including this page — lives alongside Localize
    itself on GitHub. Fixes and typos are welcome as pull requests.
  </p>
  """

config :static_blog, :r2,
  bucket: "content",
  prefix: "blog",
  region: "auto"

config :static_blog, :auth_token_env_var, "LOCALIZE_BLOG_TOKEN"
